name: Deploy to Lambda

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      node-version:
        required: true
        type: string
      lambda-url:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_REGION:
        required: true
      FUNCTION_NAME:
        required: true
      S3_BUCKET:
        required: true

jobs:
  prepare:
    name: Prepare For Deployment
    runs-on: ubuntu-latest
    outputs:
      sha: ${{ steps.get-sha.outputs.SHA }}
    steps:
      - name: Get SHA
        id: get-sha
        run: echo "SHA=${GITHUB_SHA:0:8}" >> $GITHUB_OUTPUT

  deploy:
    name: Deploy to Lambda
    needs: [ prepare ]
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
      url: ${{ inputs.lambda-url }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}

      - name: Install Node dependencies
        run: |
          npm pkg delete scripts.prepare && npm ci --only=prod --omit=dev

      - name: Zip Package
        run: zip -rq lambda.zip node_modules index.js index.mjs

      - name: Call Reusable Workflow for Deployment
        uses: checkout-org/.github/.github/workflows/deploy-lambda-node.yml@master
        with:
          sha: ${{ needs.prepare.outputs.sha }}
          s3-bucket: ${{ secrets.S3_BUCKET }}
          function-name: ${{ secrets.FUNCTION_NAME }}
          version-alias: ${{ vars.VERSION_ALIAS }}
